name: "k8 object creation"
description: "This action helps in creating new object in a k8 cluster"
branding:
  color: green
  icon: shield

inputs:
  KubeconfigFile:
    description: "kubeconfig file to login into k8 cluster"
    required: true
  ObjectsFile:
    description: "yaml file to create objects in k8 cluster"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.KubeconfigFile }}
    - ${{ inputs.ObjectsFile }}
