name: "k8 commands"
description: "execute"
branding:
  color: green
  icon: shield

inputs:
  kubefile:
    description: "input"
    required: true
  command:
    description: "execute"
    required: true

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.kubefile }}
    - ${{ inputs.command }}
