on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: "get namespace"
      uses: Thirumal-Palwai/k8_test@V1.0

      with:
        kubefile: help
        command: get
